
export enum AppActionType {
    SET_BASE_CURRENCY = 'SET_BASE_CURRENCY',
    SET_LATEST_RATES = 'SET_LATEST_RATES',
    SET_HISTORICAL_RATES = 'SET_HISTORICAL_RATES',
    SET_SUPPORTED_CURRENCIES = 'SET_SUPPORTED_CURRENCIES',
    SET_CONVERT_CURRENCIES = 'SET_CONVERT_CURRENCIES',
    SET_TIME_SERIES_RATES = 'SET_TIME_SERIES_RATES',
    LATEST_RATES_REQUEST = 'LATEST_RATES_REQUEST',
    LATEST_RATES_SUCCESS = 'LATEST_RATES_SUCCESS',
    LATEST_RATES_FAILURE = 'LATEST_RATES_FAILURE',
    HISTORICAL_RATES_REQUEST = 'HISTORICAL_RATES_REQUEST',
    HISTORICAL_RATES_SUCCESS = 'HISTORICAL_RATES_SUCCESS',
    HISTORICAL_RATES_FAILURE = 'HISTORICAL_RATES_FAILURE',
    SUPPORTED_CURRENCIES_REQUEST = 'SUPPORTED_CURRENCIES_REQUEST',
    SUPPORTED_CURRENCIES_SUCCESS = 'SUPPORTED_CURRENCIES_SUCCESS',
    SUPPORTED_CURRENCIES_FAILURE = 'SUPPORTED_CURRENCIES_FAILURE',
    CONVERT_CURRENCIES_REQUEST = 'CONVERT_CURRENCIES_REQUEST',
    CONVERT_CURRENCIES_SUCCESS = 'CONVERT_CURRENCIES_SUCCESS',
    CONVERT_CURRENCIES_FAILURE = 'CONVERT_CURRENCIES_FAILURE',
    TIME_SERIES_RATES_REQUEST = 'TIME_SERIES_RATES_REQUEST',
    TIME_SERIES_RATES_SUCCESS = 'TIME_SERIES_RATES_SUCCESS',
    TIME_SERIES_RATES_FAILURE = 'TIME_SERIES_RATES_FAILURE',
    
}

